{"name": "test_personal_info_verification[chromium]", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <Suites.Users_profile.users_profile.PersonalInfVer object at 0x0000021FFC6D3F80>\n\n    @allure.step('Confirm login')\n    def press_confirm_log_in_button(self):\n        try:\n>           self.confirm_log_in_button.click()\n\nSuites\\Base\\BaseSetUp.py:55: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:14851: in click\n    self._sync(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_locator.py:153: in click\n    return await self._frame.click(self._selector, strict=True, **params)\n.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py:488: in click\n    await self._channel.send(\"click\", locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:59: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x0000021FFBD93B00>, cb = <function Channel.send.<locals>.<lambda> at 0x0000021FFC744F40>, is_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nE           Call log:\nE           waiting for locator(\"//button[contains(@class, 'min-w-full') and contains(text(),'Log in')]\")\n\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:513: TimeoutError\n\nThe above exception was the direct cause of the following exception:\n\nself = <Suites.Users_profile.users_profile.PersonalInfVer object at 0x0000021FFC6D3F80>\n\n    def set_up(self):\n        try:\n>           super().set_up()\n\nSuites\\Users_profile\\users_profile.py:11: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nSuites\\Base\\BaseSetUp.py:81: in set_up\n    self.press_confirm_log_in_button()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Suites.Users_profile.users_profile.PersonalInfVer object at 0x0000021FFC6D3F80>\n\n    @allure.step('Confirm login')\n    def press_confirm_log_in_button(self):\n        try:\n            self.confirm_log_in_button.click()\n            time.sleep(5)\n            allure.attach(self.page.screenshot(), name='Log in button pressed',\n                          attachment_type=allure.attachment_type.PNG)\n            self.page.goto('https://tombriches.com/')\n    \n        except Exception as e:\n            allure.attach(self.page.screenshot(), name='Log in button is not pressed',\n                          attachment_type=allure.attachment_type.PNG)\n>           raise AssertionError from e\nE           AssertionError\n\nSuites\\Base\\BaseSetUp.py:64: AssertionError\n\nThe above exception was the direct cause of the following exception:\n\npage = <Page url='https://tombriches.com/'>\n\n    @allure.suite(\"Users profile suite\")\n    def test_personal_info_verification(page):\n        personal_info_verification = PersonalInfVer(page)\n>       personal_info_verification.set_up()\n\ntest_tr_smoke.py:86: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Suites.Users_profile.users_profile.PersonalInfVer object at 0x0000021FFC6D3F80>\n\n    def set_up(self):\n        try:\n            super().set_up()\n            allure.attach(self.page.screenshot(), name='Set up passed', attachment_type=allure.attachment_type.PNG)\n    \n        except Exception as e:\n            allure.attach(self.page.screenshot(), name='Set up failed', attachment_type=allure.attachment_type.PNG)\n>           raise AssertionError from e\nE           AssertionError\n\nSuites\\Users_profile\\users_profile.py:16: AssertionError"}, "steps": [{"name": "Press on Log in button", "status": "passed", "attachments": [{"name": "Log in button pressed", "source": "fdf5c794-6017-4397-8465-30a8006546ec-attachment.png", "type": "image/png"}], "start": 1714566602667, "stop": 1714566603000}, {"name": "Enter credentials", "status": "passed", "attachments": [{"name": "E-mail field filled", "source": "c0883ae3-9469-4e58-9404-1838c0be8899-attachment.png", "type": "image/png"}, {"name": "Password field filled", "source": "c7426062-0aae-4776-bcb4-9ce709824342-attachment.png", "type": "image/png"}], "start": 1714566603000, "stop": 1714566603462}, {"name": "Confirm login", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\User\\Desktop\\Automation\\TR_Smoke\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\Desktop\\Automation\\TR_Smoke\\Suites\\Base\\BaseSetUp.py\", line 64, in press_confirm_log_in_button\n    raise AssertionError from e\n"}, "attachments": [{"name": "Log in button is not pressed", "source": "492cb825-1230-4947-a917-e44787a48d9c-attachment.png", "type": "image/png"}], "start": 1714566603462, "stop": 1714566633660}], "attachments": [{"name": "Page open", "source": "691bb09f-db57-4c49-8db1-b8412cf41cf9-attachment.png", "type": "image/png"}, {"name": "Set up failed", "source": "409c2072-9dbe-45dd-852d-87b9b274e985-attachment.png", "type": "image/png"}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1714566599805, "stop": 1714566633838, "uuid": "f58a7f60-1db2-4d53-b619-daf936cddb6e", "historyId": "ffa91ff9d54823d31b1a2196955bc70f", "testCaseId": "cd09cbf823bb6ec81d1698d5cfa5f054", "fullName": "test_tr_smoke#test_personal_info_verification", "labels": [{"name": "suite", "value": "Users profile suite"}, {"name": "host", "value": "DESKTOP-EFHMBBJ"}, {"name": "thread", "value": "25980-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_tr_smoke"}]}