{"name": "test_providers_dropdown[chromium]", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <Suites.Game.providers_test.ProvidersTest object at 0x0000021FFC70ED80>\n\n    @allure.step('Confirm login')\n    def press_confirm_log_in_button(self):\n        try:\n>           self.confirm_log_in_button.click()\n\nSuites\\Base\\BaseSetUp.py:55: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:14851: in click\n    self._sync(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_locator.py:153: in click\n    return await self._frame.click(self._selector, strict=True, **params)\n.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py:488: in click\n    await self._channel.send(\"click\", locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:59: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x0000021FFBD93B00>, cb = <function Channel.send.<locals>.<lambda> at 0x0000021FFC696F20>, is_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.\nE           Call log:\nE           waiting for locator(\"//button[contains(@class, 'min-w-full') and contains(text(),'Log in')]\")\n\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:513: TimeoutError\n\nThe above exception was the direct cause of the following exception:\n\nself = <Suites.Game.providers_test.ProvidersTest object at 0x0000021FFC70ED80>\n\n    def set_up(self):\n        try:\n>           super().set_up()\n\nSuites\\Game\\providers_test.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nSuites\\Base\\BaseSetUp.py:81: in set_up\n    self.press_confirm_log_in_button()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Suites.Game.providers_test.ProvidersTest object at 0x0000021FFC70ED80>\n\n    @allure.step('Confirm login')\n    def press_confirm_log_in_button(self):\n        try:\n            self.confirm_log_in_button.click()\n            time.sleep(5)\n            allure.attach(self.page.screenshot(), name='Log in button pressed',\n                          attachment_type=allure.attachment_type.PNG)\n            self.page.goto('https://tombriches.com/')\n    \n        except Exception as e:\n            allure.attach(self.page.screenshot(), name='Log in button is not pressed',\n                          attachment_type=allure.attachment_type.PNG)\n>           raise AssertionError from e\nE           AssertionError\n\nSuites\\Base\\BaseSetUp.py:64: AssertionError\n\nThe above exception was the direct cause of the following exception:\n\npage = <Page url='https://tombriches.com/'>\n\n    @allure.suite(\"Game suite\")\n    def test_providers_dropdown(page):\n        providers = ProvidersTest(page)\n>       providers.set_up()\n\ntest_tr_smoke.py:80: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Suites.Game.providers_test.ProvidersTest object at 0x0000021FFC70ED80>\n\n    def set_up(self):\n        try:\n            super().set_up()\n        except Exception as e:\n            allure.attach(self.page.screenshot(), name='Set up failed', attachment_type=allure.attachment_type.PNG)\n>           raise AssertionError from e\nE           AssertionError\n\nSuites\\Game\\providers_test.py:16: AssertionError"}, "steps": [{"name": "Press on Log in button", "status": "passed", "attachments": [{"name": "Log in button pressed", "source": "e9e2a41b-8c0a-4192-911a-830620f005d5-attachment.png", "type": "image/png"}], "start": 1714566568552, "stop": 1714566568857}, {"name": "Enter credentials", "status": "passed", "attachments": [{"name": "E-mail field filled", "source": "5883c17d-2843-45ff-aa52-71c45ad77012-attachment.png", "type": "image/png"}, {"name": "Password field filled", "source": "ded86001-4e25-4c3a-89d9-0d5902ebedc9-attachment.png", "type": "image/png"}], "start": 1714566568857, "stop": 1714566569239}, {"name": "Confirm login", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"C:\\Users\\User\\Desktop\\Automation\\TR_Smoke\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\Desktop\\Automation\\TR_Smoke\\Suites\\Base\\BaseSetUp.py\", line 64, in press_confirm_log_in_button\n    raise AssertionError from e\n"}, "attachments": [{"name": "Log in button is not pressed", "source": "621ba4ad-27e9-4efd-92fa-511b7af96db6-attachment.png", "type": "image/png"}], "start": 1714566569240, "stop": 1714566599416}], "attachments": [{"name": "Page open", "source": "260b5680-0e33-4ca3-9d19-0ad3a38eb7f5-attachment.png", "type": "image/png"}, {"name": "Set up failed", "source": "d911bb85-bf1c-4e8d-b170-fca70a6ba73b-attachment.png", "type": "image/png"}], "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1714566564890, "stop": 1714566599589, "uuid": "28d6220e-8af5-4965-8b9c-0d4185a72abd", "historyId": "cdf5409863b109bab4d835a730ef5f29", "testCaseId": "65bc690e6329b3e337214de2eae7b522", "fullName": "test_tr_smoke#test_providers_dropdown", "labels": [{"name": "suite", "value": "Game suite"}, {"name": "host", "value": "DESKTOP-EFHMBBJ"}, {"name": "thread", "value": "25980-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_tr_smoke"}]}